project_name: influx-cli

# Do not make github release
release:
  disable: true

builds:
  - id: influx
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64
    main: ./cmd/influx
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{if .IsSnapshot}}{{.Env.SNAPSHOT_VERSION}}{{else}}{{.Version}}{{end}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    binary: influx

nfpms:
  - id: influx-cli
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    conflicts:
      - influxdb
    overrides:
      rpm:
        replacements:
          amd64: x86_64
          arm64: aarch64
          armhf: armv7hl
        file_name_template: influxdb2-client-{{if .IsSnapshot}}{{.Env.SNAPSHOT_PACKAGE_TAG}}{{else}}{{.Version}}{{end}}.{{ .Arch }}
      deb:
        replaces:
          # Tells the deb system that it's ok for this package to overwrite files from versions of the `influxdb2`
          # package prior to 2.1.0. Needed to support installing `influx-cli` next to `influxdb` without upgrading
          # the server.
          #
          # NOTE: rpm doesn't have an equivalent feature (the closest thing is to mark influx-cli as replacing
          # `influxdb2`, which auto-uninstalls the server). Without that data, `yum install influx-cli` won't work
          # when `influxdb2` is already installed. Users can work around this by downloading the RPM directly
          # and then using `rpm -i --replacefiles <the-rpm>`.
          - influxdb2 (<< 2.1.0)
        file_name_template: influxdb2-client-{{if .IsSnapshot}}{{.Env.SNAPSHOT_PACKAGE_TAG}}{{else}}{{.Version}}{{end}}-{{ .Arch }}
    vendor: InfluxData
    homepage: https://influxdata.com
    maintainer: support@influxdata.com
    description: CLI for managing resources in InfluxDB v2
    license: MIT

archives:
  - id: influx-cli
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    name_template: influxdb2-client-{{if .IsSnapshot}}{{.Env.SNAPSHOT_PACKAGE_TAG}}{{else}}{{.Version}}{{end}}-{{ .Os }}-{{ .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: influxdb2-client-{{if .IsSnapshot}}{{.Env.SNAPSHOT_PACKAGE_TAG}}{{else}}{{.Version}}{{end}}.sha256
  algorithm: sha256

signs:
  - signature: "${artifact}.asc"
    cmd: gpg
    args: [ --passphrase, "{{.Env.PASSPHRASE}}", --pinentry-mode=loopback, --batch, --armor, --detach-sign, "${artifact}"]
    artifacts: all

blobs:
  - provider: s3
    bucket: dl.influxdata.com
    region: us-east-1
    folder: "{{if .IsSnapshot}}platform/nightlies/{{else}}influxdb/releases/{{end}}"
