project_name: influx-cli

# Do not make github release
release:
  disable: true

builds:
  - id: influx
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64
    main: ./cmd/influx
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{if .IsSnapshot}}{{.Env.SNAPSHOT_VERSION}}{{else}}{{.Version}}{{end}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    binary: influx

# TODO: Do we want to publish deb/rpms for the CLI before we release 2.1.0 of the server?
# How do we handle conflicts between the two until then?
nfpms:
  - id: influx-cli
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    overrides:
      rpm:
        replacements:
          amd64: x86_64
          arm64: aarch64
          armhf: armv7hl
        file_name_template: influx-cli-nightly.{{ .Arch }}
      deb:
        file_name_template: influx-cli-nightly-{{ .Arch }}
    vendor: InfluxData
    homepage: https://influxdata.com
    maintainer: support@influxdata.com
    description: CLI for managing resources in InfluxDB v2
    license: MIT

archives:
  - id: influx-cli
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    name_template: influx-cli-nightly-{{ .Os }}-{{ .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: influx-cli-nightly.sha256
  algorithm: sha256

# TODO: Do we want to do this signing work in Circle? Or elsewhere?
signs:
  - signature: "${artifact}.asc"
    cmd: gpg
    args: [ --passphrase, "{{.Env.PASSPHRASE}}", --pinentry-mode=loopback, --batch, --armor, --detach-sign, "${artifact}"]
    artifacts: all

blobs:
  - provider: s3
    bucket: dl.influxdata.com
    region: us-east-1
    folder: platform/nightlies/
