openapi: "3.0.0"
info:
  title: Extra configuration to force openapi to generate enum validators
  version: 2.0.0
servers: []
paths: {}
components:
  schemas:
    ResourceEnumOSS:
      $ref: "./openapi/src/oss/schemas/Resource.yml#/properties/type"
    ResourceEnumCloud:
      $ref: "./openapi/src/cloud/schemas/Resource.yml#/properties/type"

