openapi: "3.0.0"
info:
  title: Subset of Influx API covered by Influx CLI
  version: 2.0.0
servers:
  - url: /
paths:
  /query:
    $ref: "./overrides/paths/legacy_query.yml"
  /health:
    $ref: "./openapi/src/oss/paths/health.yml"
  /ping:
    $ref: "./overrides/paths/ping.yml"
  /private/legacy/authorizations:
    $ref: "./openapi/src/oss/paths/legacy_authorizations.yml"
  /private/legacy/authorizations/{authID}:
    $ref: "./openapi/src/oss/paths/legacy_authorizations_authID.yml"
  /private/legacy/authorizations/{authID}/password:
    $ref: "./openapi/src/oss/paths/legacy_authorizations_authID_password.yml"
  /api/v2/setup:
    $ref: "./openapi/src/common/paths/setup.yml"
  /api/v2/write:
    $ref: "./openapi/src/common/paths/write.yml"
  /api/v2/buckets:
    $ref: "./openapi/src/common/paths/buckets.yml"
  /api/v2/buckets/{bucketID}:
    $ref: "./openapi/src/common/paths/buckets_bucketID.yml"
  /api/v2/orgs:
    $ref: "./openapi/src/common/paths/orgs.yml"
  /api/v2/orgs/{orgID}:
    $ref: "./openapi/src/common/paths/orgs_orgID.yml"
  /api/v2/orgs/{orgID}/members:
    $ref: "./openapi/src/common/paths/orgs_orgID_members.yml"
  /api/v2/orgs/{orgID}/members/{userID}:
    $ref: "./openapi/src/common/paths/orgs_orgID_members_userID.yml"
  /api/v2/orgs/{orgID}/secrets:
    $ref: "./openapi/src/common/paths/orgs_orgID_secrets.yml"
  /api/v2/orgs/{orgID}/secrets/{delete}:
    $ref: "./openapi/src/common/paths/orgs_orgID_secrets_delete.yml"
  /api/v2/buckets/{bucketID}/schema/measurements:
    $ref: "./openapi/src/cloud/paths/measurements.yml"
  /api/v2/buckets/{bucketID}/schema/measurements/{measurementID}:
    $ref: "./openapi/src/cloud/paths/measurements_measurementID.yml"
  /api/v2/query:
    $ref: "./overrides/paths/query.yml"
  /api/v2/users:
    $ref: "./openapi/src/common/paths/users.yml"
  /api/v2/users/{userID}:
    $ref: "./openapi/src/common/paths/users_userID.yml"
  "/api/v2/users/{userID}/password":
    $ref: "./openapi/src/common/paths/users_userID_password.yml"
  /api/v2/delete:
    $ref: "./openapi/src/common/paths/delete.yml"
  /api/v2/tasks:
    $ref: "./openapi/src/common/paths/tasks.yml"
  /api/v2/tasks/{taskID}:
    $ref: "./openapi/src/common/paths/tasks_taskID.yml"
  /api/v2/tasks/{taskID}/runs:
    $ref: "./openapi/src/common/paths/tasks_taskID_runs.yml"
  /api/v2/tasks/{taskID}/runs/{runID}:
    $ref: "./openapi/src/common/paths/tasks_taskID_runs_runID.yml"
  /api/v2/tasks/{taskID}/runs/{runID}/retry:
    $ref: "./openapi/src/common/paths/tasks_taskID_runs_runID_retry.yml"
  /api/v2/tasks/{taskID}/logs:
    $ref: "./openapi/src/common/paths/tasks_taskID_logs.yml"
  /api/v2/tasks/{taskID}/runs/{runID}/logs:
    $ref: "./openapi/src/common/paths/tasks_taskID_runs_runID_logs.yml"
  /api/v2/backup/kv:
    $ref: "./openapi/src/oss/paths/backup_kv.yml"
  /api/v2/backup/metadata:
    $ref: "./overrides/paths/backup_metadata.yml"
  /api/v2/backup/shards/{shardID}:
    $ref: "./openapi/src/oss/paths/backup_shards_shardID.yml"
  /api/v2/resources:
    $ref: "./openapi/src/common/paths/resources.yml"
  /api/v2/restore/kv:
    $ref: "./openapi/src/oss/paths/restore_kv.yml"
  /api/v2/restore/sql:
    $ref: "./openapi/src/oss/paths/restore_sql.yml"
  /api/v2/restore/buckets/{bucketID}:
    $ref: "./openapi/src/oss/paths/restore_bucket_bucketID.yml"
  /api/v2/restore/bucketMetadata:
    $ref: "./openapi/src/oss/paths/restore_bucketMetadata.yml"
  /api/v2/restore/shards/{shardID}:
    $ref: "./openapi/src/oss/paths/restore_shards_shardID.yml"
  "/api/v2/telegrafs":
    $ref: "./openapi/src/common/paths/telegrafs.yml"
  "/api/v2/telegrafs/{telegrafID}":
    $ref: "./overrides/paths/telegrafs_telegrafID.yml"
  /api/v2/dashboards:
    $ref: "./overrides/paths/dashboards.yml"
  /api/v2/templates/export:
    $ref: "./overrides/paths/templates_export.yml"
  /api/v2/templates/apply:
    $ref: "./overrides/paths/templates_apply.yml"
  /api/v2/stacks:
    $ref: "./overrides/paths/stacks.yml"
  /api/v2/stacks/{stack_id}:
    $ref: "./overrides/paths/stacks_stack_id.yml"
  /api/v2/dbrps:
    $ref: "./openapi/src/common/paths/dbrps.yml"
  "/api/v2/dbrps/{dbrpID}":
    $ref: "./openapi/src/common/paths/dbrps_dbrpID.yml"
  /api/v2/authorizations:
    $ref: "./openapi/src/common/paths/authorizations.yml"
  /api/v2/authorizations/{authID}:
    $ref: "./openapi/src/common/paths/authorizations_authID.yml"
  /api/v2/remotes:
    $ref: "./openapi/src/oss/paths/remotes.yml"
  /api/v2/remotes/{remoteID}:
    $ref: "./openapi/src/oss/paths/remotes_remoteID.yml"
  /api/v2/replications:
    $ref: "./openapi/src/oss/paths/replications.yml"
  /api/v2/replications/{replicationID}:
    $ref: "./openapi/src/oss/paths/replications_replicationID.yml"
  /api/v2/replications/{replicationID}/validate:
    $ref: "./openapi/src/oss/paths/replications_replicationID_validate.yml"
  /api/v2/config:
    $ref: "./openapi/src/oss/paths/config.yml"
components:
  parameters:
    TraceSpan:
      $ref: "./openapi/src/common/parameters/TraceSpan.yml"
    Offset:
      $ref: "./openapi/src/common/parameters/Offset.yml"
    Limit:
      $ref: "./openapi/src/common/parameters/Limit.yml"
    After:
      $ref: "./openapi/src/common/parameters/After.yml"
    Descending:
      $ref: "./openapi/src/common/parameters/Descending.yml"
  responses:
    ServerError:
      $ref: "./openapi/src/common/responses/ServerError.yml"
  schemas:
    Error:
      $ref: "./openapi/src/common/schemas/Error.yml"
    ErrorCode:
      $ref: "./openapi/src/common/schemas/ErrorCode.yml"
    HealthCheck:
      $ref: "./openapi/src/common/schemas/HealthCheck.yml"
    HealthCheckStatus:
      $ref: "./openapi/src/common/schemas/HealthCheckStatus.yml"
    OnboardingRequest:
      $ref: "./openapi/src/common/schemas/OnboardingRequest.yml"
    OnboardingResponse:
      $ref: "./openapi/src/common/schemas/OnboardingResponse.yml"
    Users:
      $ref: "./openapi/src/common/schemas/Users.yml"
    User:
      $ref: "./openapi/src/common/schemas/User.yml"
    UserResponse:
      $ref: "./openapi/src/common/schemas/UserResponse.yml"
    PasswordResetBody:
      $ref: "./openapi/src/common/schemas/PasswordResetBody.yml"
    Links:
      $ref: "./openapi/src/common/schemas/Links.yml"
    Link:
      $ref: "./openapi/src/common/schemas/Link.yml"
    Organizations:
      $ref: "./openapi/src/common/schemas/Organizations.yml"
    Organization:
      $ref: "./openapi/src/common/schemas/Organization.yml"
    PostOrganizationRequest:
      $ref: "./openapi/src/common/schemas/PostOrganizationRequest.yml"
    PatchOrganizationRequest:
      $ref: "./openapi/src/common/schemas/PatchOrganizationRequest.yml"
    Buckets:
      $ref: "./openapi/src/common/schemas/Buckets.yml"
    Bucket:
      $ref: "./openapi/src/common/schemas/Bucket.yml"
    PostBucketRequest:
      $ref: "./openapi/src/common/schemas/PostBucketRequest.yml"
    RetentionRules:
      $ref: "./openapi/src/common/schemas/RetentionRules.yml"
    RetentionRule:
      $ref: "./openapi/src/common/schemas/RetentionRule.yml"
    PatchBucketRequest:
      $ref: "./openapi/src/common/schemas/PatchBucketRequest.yml"
    PatchRetentionRules:
      $ref: "./openapi/src/common/schemas/PatchRetentionRules.yml"
    PatchRetentionRule:
      $ref: "./openapi/src/common/schemas/PatchRetentionRule.yml"
    Labels:
      $ref: "./openapi/src/common/schemas/Labels.yml"
    Label:
      $ref: "./openapi/src/common/schemas/Label.yml"
    Authorization:
      $ref: "./openapi/src/common/schemas/Authorization.yml"
    AuthorizationUpdateRequest:
      $ref: "./openapi/src/common/schemas/AuthorizationUpdateRequest.yml"
    Permission:
      $ref: "./openapi/src/common/schemas/Permission.yml"
    ResourceMembers:
      $ref: "./openapi/src/common/schemas/ResourceMembers.yml"
    ResourceMember:
      $ref: "./openapi/src/common/schemas/ResourceMember.yml"
    AddResourceMemberRequestBody:
      $ref: "./openapi/src/common/schemas/AddResourceMemberRequestBody.yml"
    WritePrecision:
      $ref: "./openapi/src/common/schemas/WritePrecision.yml"
    LineProtocolError:
      $ref: "./openapi/src/common/schemas/LineProtocolError.yml"
    LineProtocolErrorCode:
      $ref: "./openapi/src/common/schemas/LineProtocolErrorCode.yml"
    LineProtocolLengthError:
      $ref: "./openapi/src/common/schemas/LineProtocolLengthError.yml"
    LineProtocolLengthErrorCode:
      $ref: "./openapi/src/common/schemas/LineProtocolLengthErrorCode.yml"
    SchemaType:
      $ref: "./openapi/src/common/schemas/SchemaType.yml"
    ColumnDataType:
      $ref: "./openapi/src/cloud/schemas/ColumnDataType.yml"
    ColumnSemanticType:
      $ref: "./openapi/src/cloud/schemas/ColumnSemanticType.yml"
    MeasurementSchema:
      $ref: "./openapi/src/cloud/schemas/MeasurementSchema.yml"
    MeasurementSchemaColumn:
      $ref: "./openapi/src/cloud/schemas/MeasurementSchemaColumn.yml"
    MeasurementSchemaCreateRequest:
      $ref: "./openapi/src/cloud/schemas/MeasurementSchemaCreateRequest.yml"
    MeasurementSchemaList:
      $ref: "./openapi/src/cloud/schemas/MeasurementSchemaList.yml"
    MeasurementSchemaUpdateRequest:
      $ref: "./openapi/src/cloud/schemas/MeasurementSchemaUpdateRequest.yml"
    Query:
      $ref: "./overrides/schemas/Query.yml"
    InfluxqlCsvResponse:
      $ref: "./overrides/schemas/InfluxqlCsvResponse.yml"
    InfluxqlJsonResponse:
      $ref: "./overrides/schemas/InfluxqlJsonResponse.yml"
    Dialect:
      $ref: "./openapi/src/common/schemas/Dialect.yml"
    Extern:
      $ref: "./overrides/schemas/Extern.yml"
    DeletePredicateRequest:
      $ref: "./openapi/src/common/schemas/DeletePredicateRequest.yml"
    Tasks:
      $ref: "./openapi/src/common/schemas/Tasks.yml"
    Task:
      $ref: "./openapi/src/common/schemas/Task.yml"
    TaskCreateRequest:
      $ref: "./openapi/src/common/schemas/TaskCreateRequest.yml"
    TaskStatusType:
      $ref: "./openapi/src/common/schemas/TaskStatusType.yml"
    TaskUpdateRequest:
      $ref: "./openapi/src/common/schemas/TaskUpdateRequest.yml"
    Runs:
      $ref: "./openapi/src/common/schemas/Runs.yml"
    Run:
      $ref: "./openapi/src/common/schemas/Run.yml"
    RunManually:
      $ref: "./openapi/src/common/schemas/RunManually.yml"
    Logs:
      $ref: "./openapi/src/common/schemas/Logs.yml"
    LogEvent:
      $ref: "./openapi/src/common/schemas/LogEvent.yml"
    MetadataBackup:
      $ref: "./openapi/src/oss/schemas/MetadataBackup.yml"
    BucketMetadataManifests:
      $ref: "./openapi/src/oss/schemas/BucketMetadataManifests.yml"
    BucketMetadataManifest:
      $ref: "./openapi/src/oss/schemas/BucketMetadataManifest.yml"
    RetentionPolicyManifests:
      $ref: "./openapi/src/oss/schemas/RetentionPolicyManifests.yml"
    RetentionPolicyManifest:
      $ref: "./openapi/src/oss/schemas/RetentionPolicyManifest.yml"
    ShardGroupManifests:
      $ref: "./openapi/src/oss/schemas/ShardGroupManifests.yml"
    ShardGroupManifest:
      $ref: "./openapi/src/oss/schemas/ShardGroupManifest.yml"
    ShardManifests:
      $ref: "./openapi/src/oss/schemas/ShardManifests.yml"
    ShardManifest:
      $ref: "./openapi/src/oss/schemas/ShardManifest.yml"
    ShardOwners:
      $ref: "./openapi/src/oss/schemas/ShardOwners.yml"
    ShardOwner:
      $ref: "./openapi/src/oss/schemas/ShardOwner.yml"
    SubscriptionManifests:
      $ref: "./openapi/src/oss/schemas/SubscriptionManifests.yml"
    SubscriptionManifest:
      $ref: "./openapi/src/oss/schemas/SubscriptionManifest.yml"
    RestoredBucketMappings:
      $ref: "./openapi/src/oss/schemas/RestoredBucketMappings.yml"
    BucketShardMappings:
      $ref: "./openapi/src/oss/schemas/BucketShardMappings.yml"
    BucketShardMapping:
      $ref: "./openapi/src/oss/schemas/BucketShardMapping.yml"
    PostRestoreKVResponse:
      $ref: "./openapi/src/oss/schemas/PostRestoreKVResponse.yml"
    Telegrafs:
      $ref: "./openapi/src/common/schemas/Telegrafs.yml"
    TelegrafRequest:
      $ref: "./openapi/src/common/schemas/TelegrafRequest.yml"
    TelegrafPluginRequest:
      $ref: "./openapi/src/common/schemas/TelegrafPluginRequest.yml"
    Telegraf:
      $ref: "./openapi/src/common/schemas/Telegraf.yml"
    Dashboards:
      $ref: "./openapi/src/common/schemas/Dashboards.yml"
    Dashboard:
      $ref: "./openapi/src/common/schemas/Dashboard.yml"
    CreateDashboardRequest:
      $ref: "./openapi/src/common/schemas/CreateDashboardRequest.yml"
    Cells:
      $ref: "./openapi/src/common/schemas/Cells.yml"
    Cell:
      $ref: "./openapi/src/common/schemas/Cell.yml"
    TemplateExport:
      $ref: "./overrides/schemas/TemplateExport.yml"
    Template:
      $ref: "./overrides/schemas/Template.yml"
    TemplateEntry:
      $ref: "./overrides/schemas/TemplateEntry.yml"
    TemplateApply:
      $ref: "./overrides/schemas/TemplateApply.yml"
    TemplateApplyTemplate:
      $ref: "./overrides/schemas/TemplateApplyTemplate.yml"
    TemplateApplyRemoteRef:
      $ref: "./overrides/schemas/TemplateApplyRemoteRef.yml"
    TemplateApplyAction:
      $ref: "./overrides/schemas/TemplateApplyAction.yml"
    TemplateApplyActionKind:
      $ref: "./overrides/schemas/TemplateApplyActionKind.yml"
    TemplateSummary:
      $ref: "./overrides/schemas/TemplateSummary.yml"
    TemplateSummaryResources:
      $ref: "./overrides/schemas/TemplateSummaryResources.yml"
    TemplateSummaryError:
      $ref: "./overrides/schemas/TemplateSummaryError.yml"
    TemplateSummaryErrors:
      $ref: "./overrides/schemas/TemplateSummaryErrors.yml"
    TemplateSummaryBucket:
      $ref: "./overrides/schemas/TemplateSummaryBucket.yml"
    TemplateSummaryCheck:
      $ref: "./overrides/schemas/TemplateSummaryCheck.yml"
    TemplateSummaryCommon:
      $ref: "./overrides/schemas/TemplateSummaryCommon.yml"
    TemplateSummaryCore:
      $ref: "./overrides/schemas/TemplateSummaryCore.yml"
    TemplateEnvReference:
      $ref: "./overrides/schemas/TemplateEnvReference.yml"
    TemplateSummaryDashboard:
      $ref: "./overrides/schemas/TemplateSummaryDashboard.yml"
    TemplateSummaryLabel:
      $ref: "./overrides/schemas/TemplateSummaryLabel.yml"
    TemplateSummaryLabelMapping:
      $ref: "./overrides/schemas/TemplateSummaryLabelMapping.yml"
    TemplateSummaryNotificationEndpoint:
      $ref: "./overrides/schemas/TemplateSummaryNotificationEndpoint.yml"
    TemplateSummaryNotificationRule:
      $ref: "./overrides/schemas/TemplateSummaryNotificationRule.yml"
    TemplateSummaryTask:
      $ref: "./overrides/schemas/TemplateSummaryTask.yml"
    TemplateSummaryTelegraf:
      $ref: "./overrides/schemas/TemplateSummaryTelegraf.yml"
    TemplateSummaryTelegrafConfig:
      $ref: "./overrides/schemas/TemplateSummaryTelegrafConfig.yml"
    TemplateSummaryVariable:
      $ref: "./overrides/schemas/TemplateSummaryVariable.yml"
    TemplateSummaryVariableArgs:
      $ref: "./overrides/schemas/TemplateSummaryVariableArgs.yml"
    TemplateSummaryDiff:
      $ref: "./overrides/schemas/TemplateSummaryDiff.yml"
    TemplateSummaryDiffBucket:
      $ref: "./overrides/schemas/TemplateSummaryDiffBucket.yml"
    TemplateSummaryDiffBucketFields:
      $ref: "./overrides/schemas/TemplateSummaryDiffBucketFields.yml"
    TemplateSummaryDiffCheck:
      $ref: "./overrides/schemas/TemplateSummaryDiffCheck.yml"
    TemplateSummaryDiffCheckFields:
      $ref: "./overrides/schemas/TemplateSummaryDiffCheckFields.yml"
    TemplateSummaryDiffDashboard:
      $ref: "./overrides/schemas/TemplateSummaryDiffDashboard.yml"
    TemplateSummaryDiffDashboardFields:
      $ref: "./overrides/schemas/TemplateSummaryDiffDashboardFields.yml"
    TemplateSummaryDiffLabel:
      $ref: "./overrides/schemas/TemplateSummaryDiffLabel.yml"
    TemplateSummaryDiffLabelFields:
      $ref: "./overrides/schemas/TemplateSummaryDiffLabelFields.yml"
    TemplateSummaryDiffLabelMapping:
      $ref: "./overrides/schemas/TemplateSummaryDiffLabelMapping.yml"
    TemplateSummaryDiffNotificationEndpoint:
      $ref: "./overrides/schemas/TemplateSummaryDiffNotificationEndpoint.yml"
    TemplateSummaryDiffNotificationEndpointFields:
      $ref: "./overrides/schemas/TemplateSummaryDiffNotificationEndpointFields.yml"
    TemplateSummaryDiffNotificationRule:
      $ref: "./overrides/schemas/TemplateSummaryDiffNotificationRule.yml"
    TemplateSummaryDiffNotificationRuleFields:
      $ref: "./overrides/schemas/TemplateSummaryDiffNotificationRuleFields.yml"
    TemplateSummaryDiffTask:
      $ref: "./overrides/schemas/TemplateSummaryDiffTask.yml"
    TemplateSummaryDiffTaskFields:
      $ref: "./overrides/schemas/TemplateSummaryDiffTaskFields.yml"
    TemplateSummaryDiffTelegraf:
      $ref: "./overrides/schemas/TemplateSummaryDiffTelegraf.yml"
    TemplateSummaryDiffVariable:
      $ref: "./overrides/schemas/TemplateSummaryDiffVariable.yml"
    TemplateSummaryDiffVariableFields:
      $ref: "./overrides/schemas/TemplateSummaryDiffVariableFields.yml"
    Stacks:
      $ref: "./overrides/schemas/Stacks.yml"
    Stack:
      $ref: "./overrides/schemas/Stack.yml"
    StackEvent:
      $ref: "./overrides/schemas/StackEvent.yml"
    StackEventResource:
      $ref: "./overrides/schemas/StackEventResource.yml"
    StackEventResourceAssociation:
      $ref: "./overrides/schemas/StackEventResourceAssociation.yml"
    StackPostRequest:
      $ref: "./overrides/schemas/StackPostRequest.yml"
    StackPatchRequest:
      $ref: "./overrides/schemas/StackPatchRequest.yml"
    StackPatchRequestResource:
      $ref: "./overrides/schemas/StackPatchRequestResource.yml"
    SecretKeysResponse:
      $ref: "./openapi/src/common/schemas/SecretKeysResponse.yml"
    SecretKeys:
      $ref: "./openapi/src/common/schemas/SecretKeys.yml"
    Secrets:
      $ref: "./openapi/src/common/schemas/Secrets.yml"
    DBRP:
      $ref: "./openapi/src/common/schemas/DBRP.yml"
    DBRPs:
      $ref: "./openapi/src/common/schemas/DBRPs.yml"
    DBRPCreate:
      $ref: "./openapi/src/common/schemas/DBRPCreate.yml"
    DBRPUpdate:
      $ref: "./openapi/src/common/schemas/DBRPUpdate.yml"
    DBRPGet:
      $ref: "./openapi/src/common/schemas/DBRPGet.yml"
    Authorizations:
      $ref: "./openapi/src/common/schemas/Authorizations.yml"
    LegacyAuthorizationPostRequest:
      $ref: "./openapi/src/oss/schemas/LegacyAuthorizationPostRequest.yml"
    AuthorizationPostRequest:
      $ref: "./openapi/src/common/schemas/AuthorizationPostRequest.yml"
    RemoteConnection:
      $ref: "./openapi/src/oss/schemas/RemoteConnection.yml"
    RemoteConnectionCreationRequest:
      $ref: "./openapi/src/oss/schemas/RemoteConnectionCreationRequest.yml"
    RemoteConnenctionUpdateRequest:
      $ref: "./openapi/src/oss/schemas/RemoteConnectionUpdateRequest.yml"
    RemoteConnections:
      $ref: "./openapi/src/oss/schemas/RemoteConnections.yml"
    Replication:
      $ref: "./openapi/src/oss/schemas/Replication.yml"
    ReplicationCreationRequest:
      $ref: "./openapi/src/oss/schemas/ReplicationCreationRequest.yml"
    ReplicationUpdateRequest:
      $ref: "./openapi/src/oss/schemas/ReplicationUpdateRequest.yml"
    Replications:
      $ref: "./openapi/src/oss/schemas/Replications.yml"
    Config:
      $ref: "./openapi/src/oss/schemas/Config.yml"
