openapi: "3.0.0"
info:
  title: Subset of Influx API covered by Influx CLI
  version: 2.0.0
servers:
  - url: /api/v2
paths:
  /health:
    servers:
      - url: ''
    $ref: "./openapi/src/oss/paths/health.yml"
  /setup:
    $ref: "./openapi/src/common/paths/setup.yml"
  /write:
    $ref: "./openapi/src/common/paths/write.yml"
  /buckets:
    $ref: "./openapi/src/common/paths/buckets.yml"
  /buckets/{bucketID}:
    $ref: "./openapi/src/common/paths/buckets_bucketID.yml"
  /orgs:
    $ref: "./openapi/src/common/paths/orgs.yml"
  /orgs/{orgID}:
    $ref: "./openapi/src/common/paths/orgs_orgID.yml"
  /orgs/{orgID}/members:
    $ref: "./openapi/src/common/paths/orgs_orgID_members.yml"
  /orgs/{orgID}/members/{userID}:
    $ref: "./openapi/src/common/paths/orgs_orgID_members_userID.yml"
  /orgs/{orgID}/secrets:
    $ref: "./openapi/src/common/paths/orgs_orgID_secrets.yml"
  /orgs/{orgID}/secrets/{delete}:
    $ref: "./openapi/src/common/paths/orgs_orgID_secrets_delete.yml"
  /buckets/{bucketID}/schema/measurements:
    $ref: "./openapi/src/cloud/paths/measurements.yml"
  /buckets/{bucketID}/schema/measurements/{measurementID}:
    $ref: "./openapi/src/cloud/paths/measurements_measurementID.yml"
  /query:
    $ref: "./overrides/paths/query.yml"
  /users:
    $ref: "./openapi/src/common/paths/users.yml"
  /users/{userID}:
    $ref: "./openapi/src/common/paths/users_userID.yml"
  "/users/{userID}/password":
    $ref: "./openapi/src/common/paths/users_userID_password.yml"
  /delete:
    $ref: "./openapi/src/common/paths/delete.yml"
  /tasks:
    $ref: "./openapi/src/common/paths/tasks.yml"
  /tasks/{taskID}:
    $ref: "./openapi/src/common/paths/tasks_taskID.yml"
  /tasks/{taskID}/runs:
    $ref: "./openapi/src/common/paths/tasks_taskID_runs.yml"
  /tasks/{taskID}/runs/{runID}:
    $ref: "./openapi/src/common/paths/tasks_taskID_runs_runID.yml"
  /tasks/{taskID}/runs/{runID}/retry:
    $ref: "./openapi/src/common/paths/tasks_taskID_runs_runID_retry.yml"
  /tasks/{taskID}/logs:
    $ref: "./openapi/src/common/paths/tasks_taskID_logs.yml"
  /tasks/{taskID}/runs/{runID}/logs:
    $ref: "./openapi/src/common/paths/tasks_taskID_runs_runID_logs.yml"
  /backup/metadata:
    $ref: "./overrides/paths/backup_metadata.yml"
  /backup/shards/{shardID}:
    $ref: "./openapi/src/oss/paths/backup_shards_shardID.yml"
  /restore/kv:
    $ref: "./openapi/src/oss/paths/restore_kv.yml"
  /restore/sql:
    $ref: "./openapi/src/oss/paths/restore_sql.yml"
  /restore/bucket-metadata:
    $ref: "./openapi/src/oss/paths/restore_bucket-metadata.yml"
  /restore/shards/{shardID}:
    $ref: "./openapi/src/oss/paths/restore_shards_shardID.yml"
  "/telegrafs":
    $ref: "./openapi/src/common/paths/telegrafs.yml"
  "/telegrafs/{telegrafID}":
    $ref: "./overrides/paths/telegrafs_telegrafID.yml"
  /dashboards:
    $ref: "./overrides/paths/dashboards.yml"
  /templates/export:
    $ref: "./overrides/paths/templates_export.yml"
components:
  parameters:
    TraceSpan:
      $ref: "./openapi/src/common/parameters/TraceSpan.yml"
    Offset:
      $ref: "./openapi/src/common/parameters/Offset.yml"
    Limit:
      $ref: "./openapi/src/common/parameters/Limit.yml"
    After:
      $ref: "./openapi/src/common/parameters/After.yml"
    Descending:
      $ref: "./openapi/src/common/parameters/Descending.yml"
  responses:
    ServerError:
      $ref: "./openapi/src/common/responses/ServerError.yml"
  schemas:
    Error:
      $ref: "./openapi/src/common/schemas/Error.yml"
    ErrorCode:
      $ref: "./openapi/src/common/schemas/ErrorCode.yml"
    HealthCheck:
      $ref: "./openapi/src/common/schemas/HealthCheck.yml"
    HealthCheckStatus:
      $ref: "./openapi/src/common/schemas/HealthCheckStatus.yml"
    OnboardingRequest:
      $ref: "./openapi/src/common/schemas/OnboardingRequest.yml"
    OnboardingResponse:
      $ref: "./openapi/src/common/schemas/OnboardingResponse.yml"
    Users:
      $ref: "./openapi/src/common/schemas/Users.yml"
    User:
      $ref: "./openapi/src/common/schemas/User.yml"
    UserResponse:
      $ref: "./openapi/src/common/schemas/UserResponse.yml"
    PasswordResetBody:
      $ref: "./openapi/src/common/schemas/PasswordResetBody.yml"
    Links:
      $ref: "./openapi/src/common/schemas/Links.yml"
    Link:
      $ref: "./openapi/src/common/schemas/Link.yml"
    Organizations:
      $ref: "./openapi/src/common/schemas/Organizations.yml"
    Organization:
      $ref: "./openapi/src/common/schemas/Organization.yml"
    PostOrganizationRequest:
      $ref: "./openapi/src/common/schemas/PostOrganizationRequest.yml"
    PatchOrganizationRequest:
      $ref: "./openapi/src/common/schemas/PatchOrganizationRequest.yml"
    Buckets:
      $ref: "./openapi/src/common/schemas/Buckets.yml"
    Bucket:
      $ref: "./openapi/src/common/schemas/Bucket.yml"
    PostBucketRequest:
      $ref: "./openapi/src/common/schemas/PostBucketRequest.yml"
    RetentionRules:
      $ref: "./openapi/src/common/schemas/RetentionRules.yml"
    RetentionRule:
      $ref: "./openapi/src/common/schemas/RetentionRule.yml"
    PatchBucketRequest:
      $ref: "./openapi/src/common/schemas/PatchBucketRequest.yml"
    PatchRetentionRules:
      $ref: "./openapi/src/common/schemas/PatchRetentionRules.yml"
    PatchRetentionRule:
      $ref: "./openapi/src/common/schemas/PatchRetentionRule.yml"
    Labels:
      $ref: "./openapi/src/common/schemas/Labels.yml"
    Label:
      $ref: "./openapi/src/common/schemas/Label.yml"
    Authorization:
      $ref: "./openapi/src/common/schemas/Authorization.yml"
    AuthorizationUpdateRequest:
      $ref: "./openapi/src/common/schemas/AuthorizationUpdateRequest.yml"
    Permission:
      $ref: "./openapi/src/common/schemas/Permission.yml"
    ResourceMembers:
      $ref: "./openapi/src/common/schemas/ResourceMembers.yml"
    ResourceMember:
      $ref: "./openapi/src/common/schemas/ResourceMember.yml"
    AddResourceMemberRequestBody:
      $ref: "./openapi/src/common/schemas/AddResourceMemberRequestBody.yml"
    WritePrecision:
      $ref: "./openapi/src/common/schemas/WritePrecision.yml"
    LineProtocolError:
      $ref: "./openapi/src/common/schemas/LineProtocolError.yml"
    LineProtocolErrorCode:
      $ref: "./openapi/src/common/schemas/LineProtocolErrorCode.yml"
    LineProtocolLengthError:
      $ref: "./openapi/src/common/schemas/LineProtocolLengthError.yml"
    LineProtocolLengthErrorCode:
      $ref: "./openapi/src/common/schemas/LineProtocolLengthErrorCode.yml"
    SchemaType:
      $ref: "./openapi/src/common/schemas/SchemaType.yml"
    ColumnDataType:
      $ref: "./openapi/src/cloud/schemas/ColumnDataType.yml"
    ColumnSemanticType:
      $ref: "./openapi/src/cloud/schemas/ColumnSemanticType.yml"
    MeasurementSchema:
      $ref: "./openapi/src/cloud/schemas/MeasurementSchema.yml"
    MeasurementSchemaColumn:
      $ref: "./openapi/src/cloud/schemas/MeasurementSchemaColumn.yml"
    MeasurementSchemaCreateRequest:
      $ref: "./openapi/src/cloud/schemas/MeasurementSchemaCreateRequest.yml"
    MeasurementSchemaList:
      $ref: "./openapi/src/cloud/schemas/MeasurementSchemaList.yml"
    MeasurementSchemaUpdateRequest:
      $ref: "./openapi/src/cloud/schemas/MeasurementSchemaUpdateRequest.yml"
    Query:
      $ref: "./overrides/schemas/Query.yml"
    Dialect:
      $ref: "./openapi/src/common/schemas/Dialect.yml"
    Extern:
      $ref: "./overrides/schemas/Extern.yml"
    DeletePredicateRequest:
      $ref: "./openapi/src/common/schemas/DeletePredicateRequest.yml"
    Tasks:
      $ref: "./openapi/src/common/schemas/Tasks.yml"
    Task:
      $ref: "./openapi/src/common/schemas/Task.yml"
    TaskCreateRequest:
      $ref: "./openapi/src/common/schemas/TaskCreateRequest.yml"
    TaskStatusType:
      $ref: "./openapi/src/common/schemas/TaskStatusType.yml"
    TaskUpdateRequest:
      $ref: "./openapi/src/common/schemas/TaskUpdateRequest.yml"
    Runs:
      $ref: "./openapi/src/common/schemas/Runs.yml"
    Run:
      $ref: "./openapi/src/common/schemas/Run.yml"
    RunManually:
      $ref: "./openapi/src/common/schemas/RunManually.yml"
    Logs:
      $ref: "./openapi/src/common/schemas/Logs.yml"
    LogEvent:
      $ref: "./openapi/src/common/schemas/LogEvent.yml"
    MetadataBackup:
      $ref: "./openapi/src/oss/schemas/MetadataBackup.yml"
    BucketMetadataManifests:
      $ref: "./openapi/src/oss/schemas/BucketMetadataManifests.yml"
    BucketMetadataManifest:
      $ref: "./openapi/src/oss/schemas/BucketMetadataManifest.yml"
    RetentionPolicyManifests:
      $ref: "./openapi/src/oss/schemas/RetentionPolicyManifests.yml"
    RetentionPolicyManifest:
      $ref: "./openapi/src/oss/schemas/RetentionPolicyManifest.yml"
    ShardGroupManifests:
      $ref: "./openapi/src/oss/schemas/ShardGroupManifests.yml"
    ShardGroupManifest:
      $ref: "./openapi/src/oss/schemas/ShardGroupManifest.yml"
    ShardManifests:
      $ref: "./openapi/src/oss/schemas/ShardManifests.yml"
    ShardManifest:
      $ref: "./openapi/src/oss/schemas/ShardManifest.yml"
    ShardOwners:
      $ref: "./openapi/src/oss/schemas/ShardOwners.yml"
    ShardOwner:
      $ref: "./openapi/src/oss/schemas/ShardOwner.yml"
    SubscriptionManifests:
      $ref: "./openapi/src/oss/schemas/SubscriptionManifests.yml"
    SubscriptionManifest:
      $ref: "./openapi/src/oss/schemas/SubscriptionManifest.yml"
    RestoredBucketMappings:
      $ref: "./openapi/src/oss/schemas/RestoredBucketMappings.yml"
    BucketShardMappings:
      $ref: "./openapi/src/oss/schemas/BucketShardMappings.yml"
    BucketShardMapping:
      $ref: "./openapi/src/oss/schemas/BucketShardMapping.yml"
    Telegrafs:
      $ref: "./openapi/src/common/schemas/Telegrafs.yml"
    TelegrafRequest:
      $ref: "./openapi/src/common/schemas/TelegrafRequest.yml"
    Telegraf:
      $ref: "./openapi/src/common/schemas/Telegraf.yml"
    Dashboards:
      $ref: "./openapi/src/common/schemas/Dashboards.yml"
    Dashboard:
      $ref: "./openapi/src/common/schemas/Dashboard.yml"
    CreateDashboardRequest:
      $ref: "./openapi/src/common/schemas/CreateDashboardRequest.yml"
    Cells:
      $ref: "./openapi/src/common/schemas/Cells.yml"
    Cell:
      $ref: "./openapi/src/common/schemas/Cell.yml"
    TemplateExport:
      $ref: "./overrides/schemas/TemplateExport.yml"
    Template:
      $ref: "./overrides/schemas/Template.yml"
    TemplateEntry:
      $ref: "./overrides/schemas/TemplateEntry.yml"
    SecretKeysResponse:
      $ref: "./openapi/src/common/schemas/SecretKeysResponse.yml"
    SecretKeys:
      $ref: "./openapi/src/common/schemas/SecretKeys.yml"
    Secrets:
      $ref: "./openapi/src/common/schemas/Secrets.yml"
