/*
 * Subset of Influx API covered by Influx CLI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// FloatLiteral Represents floating point numbers according to the double representations defined by the IEEE-754-1985
type FloatLiteral struct {
	// Type of AST node
	Type  *string  `json:"type,omitempty"`
	Value *float32 `json:"value,omitempty"`
}

// NewFloatLiteral instantiates a new FloatLiteral object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFloatLiteral() *FloatLiteral {
	this := FloatLiteral{}
	return &this
}

// NewFloatLiteralWithDefaults instantiates a new FloatLiteral object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFloatLiteralWithDefaults() *FloatLiteral {
	this := FloatLiteral{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *FloatLiteral) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FloatLiteral) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *FloatLiteral) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *FloatLiteral) SetType(v string) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *FloatLiteral) GetValue() float32 {
	if o == nil || o.Value == nil {
		var ret float32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FloatLiteral) GetValueOk() (*float32, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *FloatLiteral) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given float32 and assigns it to the Value field.
func (o *FloatLiteral) SetValue(v float32) {
	o.Value = &v
}

func (o FloatLiteral) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableFloatLiteral struct {
	value *FloatLiteral
	isSet bool
}

func (v NullableFloatLiteral) Get() *FloatLiteral {
	return v.value
}

func (v *NullableFloatLiteral) Set(val *FloatLiteral) {
	v.value = val
	v.isSet = true
}

func (v NullableFloatLiteral) IsSet() bool {
	return v.isSet
}

func (v *NullableFloatLiteral) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFloatLiteral(val *FloatLiteral) *NullableFloatLiteral {
	return &NullableFloatLiteral{value: val, isSet: true}
}

func (v NullableFloatLiteral) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFloatLiteral) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
