/*
 * Subset of Influx API covered by Influx CLI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// RegexpLiteral Expressions begin and end with `/` and are regular expressions with syntax accepted by RE2
type RegexpLiteral struct {
	// Type of AST node
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewRegexpLiteral instantiates a new RegexpLiteral object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegexpLiteral() *RegexpLiteral {
	this := RegexpLiteral{}
	return &this
}

// NewRegexpLiteralWithDefaults instantiates a new RegexpLiteral object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegexpLiteralWithDefaults() *RegexpLiteral {
	this := RegexpLiteral{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RegexpLiteral) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegexpLiteral) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RegexpLiteral) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *RegexpLiteral) SetType(v string) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *RegexpLiteral) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegexpLiteral) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *RegexpLiteral) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *RegexpLiteral) SetValue(v string) {
	o.Value = &v
}

func (o RegexpLiteral) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableRegexpLiteral struct {
	value *RegexpLiteral
	isSet bool
}

func (v NullableRegexpLiteral) Get() *RegexpLiteral {
	return v.value
}

func (v *NullableRegexpLiteral) Set(val *RegexpLiteral) {
	v.value = val
	v.isSet = true
}

func (v NullableRegexpLiteral) IsSet() bool {
	return v.isSet
}

func (v *NullableRegexpLiteral) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegexpLiteral(val *RegexpLiteral) *NullableRegexpLiteral {
	return &NullableRegexpLiteral{value: val, isSet: true}
}

func (v NullableRegexpLiteral) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegexpLiteral) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
