openapi: 3.0.0
info:
  title: Extra configuration to force openapi to generate enum validators
  version: 2.0.0
servers: []
paths: {}
components:
  schemas:
    ResourceEnumOSS:
      type: string
      enum:
        - authorizations
        - buckets
        - dashboards
        - orgs
        - sources
        - tasks
        - telegrafs
        - users
        - variables
        - scrapers
        - secrets
        - labels
        - views
        - documents
        - notificationRules
        - notificationEndpoints
        - checks
        - dbrp
        - notebooks
    ResourceEnumCloud:
      type: string
      enum:
        - authorizations
        - buckets
        - dashboards
        - orgs
        - tasks
        - telegrafs
        - users
        - variables
        - secrets
        - labels
        - views
        - documents
        - notificationRules
        - notificationEndpoints
        - checks
        - dbrp
        - flows
        - annotations
        - functions
