/*
 * Subset of Influx API covered by Influx CLI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// PatchOrganizationRequest An object that contains updated organization properties to apply.
type PatchOrganizationRequest struct {
	// The name of the organization.
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`
	// The description of the organization.
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`
}

// NewPatchOrganizationRequest instantiates a new PatchOrganizationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchOrganizationRequest() *PatchOrganizationRequest {
	this := PatchOrganizationRequest{}
	return &this
}

// NewPatchOrganizationRequestWithDefaults instantiates a new PatchOrganizationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchOrganizationRequestWithDefaults() *PatchOrganizationRequest {
	this := PatchOrganizationRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchOrganizationRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchOrganizationRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchOrganizationRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchOrganizationRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PatchOrganizationRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchOrganizationRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PatchOrganizationRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PatchOrganizationRequest) SetDescription(v string) {
	o.Description = &v
}

func (o PatchOrganizationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullablePatchOrganizationRequest struct {
	value *PatchOrganizationRequest
	isSet bool
}

func (v NullablePatchOrganizationRequest) Get() *PatchOrganizationRequest {
	return v.value
}

func (v *NullablePatchOrganizationRequest) Set(val *PatchOrganizationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchOrganizationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchOrganizationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchOrganizationRequest(val *PatchOrganizationRequest) *NullablePatchOrganizationRequest {
	return &NullablePatchOrganizationRequest{value: val, isSet: true}
}

func (v NullablePatchOrganizationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchOrganizationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
