/*
 * Subset of Influx API covered by Influx CLI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// TemplateSummaryTelegraf struct for TemplateSummaryTelegraf
type TemplateSummaryTelegraf struct {
	Kind              *string                        `json:"kind,omitempty"`
	TemplateMetaName  *string                        `json:"templateMetaName,omitempty"`
	EnvReferences     *[]TemplateEnvReference        `json:"envReferences,omitempty"`
	LabelAssociations *[]TemplateSummaryLabel        `json:"labelAssociations,omitempty"`
	TelegrafConfig    *TemplateSummaryTelegrafConfig `json:"telegrafConfig,omitempty"`
}

// NewTemplateSummaryTelegraf instantiates a new TemplateSummaryTelegraf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateSummaryTelegraf() *TemplateSummaryTelegraf {
	this := TemplateSummaryTelegraf{}
	return &this
}

// NewTemplateSummaryTelegrafWithDefaults instantiates a new TemplateSummaryTelegraf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateSummaryTelegrafWithDefaults() *TemplateSummaryTelegraf {
	this := TemplateSummaryTelegraf{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *TemplateSummaryTelegraf) GetKind() string {
	if o == nil || o.Kind == nil {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryTelegraf) GetKindOk() (*string, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *TemplateSummaryTelegraf) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *TemplateSummaryTelegraf) SetKind(v string) {
	o.Kind = &v
}

// GetTemplateMetaName returns the TemplateMetaName field value if set, zero value otherwise.
func (o *TemplateSummaryTelegraf) GetTemplateMetaName() string {
	if o == nil || o.TemplateMetaName == nil {
		var ret string
		return ret
	}
	return *o.TemplateMetaName
}

// GetTemplateMetaNameOk returns a tuple with the TemplateMetaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryTelegraf) GetTemplateMetaNameOk() (*string, bool) {
	if o == nil || o.TemplateMetaName == nil {
		return nil, false
	}
	return o.TemplateMetaName, true
}

// HasTemplateMetaName returns a boolean if a field has been set.
func (o *TemplateSummaryTelegraf) HasTemplateMetaName() bool {
	if o != nil && o.TemplateMetaName != nil {
		return true
	}

	return false
}

// SetTemplateMetaName gets a reference to the given string and assigns it to the TemplateMetaName field.
func (o *TemplateSummaryTelegraf) SetTemplateMetaName(v string) {
	o.TemplateMetaName = &v
}

// GetEnvReferences returns the EnvReferences field value if set, zero value otherwise.
func (o *TemplateSummaryTelegraf) GetEnvReferences() []TemplateEnvReference {
	if o == nil || o.EnvReferences == nil {
		var ret []TemplateEnvReference
		return ret
	}
	return *o.EnvReferences
}

// GetEnvReferencesOk returns a tuple with the EnvReferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryTelegraf) GetEnvReferencesOk() (*[]TemplateEnvReference, bool) {
	if o == nil || o.EnvReferences == nil {
		return nil, false
	}
	return o.EnvReferences, true
}

// HasEnvReferences returns a boolean if a field has been set.
func (o *TemplateSummaryTelegraf) HasEnvReferences() bool {
	if o != nil && o.EnvReferences != nil {
		return true
	}

	return false
}

// SetEnvReferences gets a reference to the given []TemplateEnvReference and assigns it to the EnvReferences field.
func (o *TemplateSummaryTelegraf) SetEnvReferences(v []TemplateEnvReference) {
	o.EnvReferences = &v
}

// GetLabelAssociations returns the LabelAssociations field value if set, zero value otherwise.
func (o *TemplateSummaryTelegraf) GetLabelAssociations() []TemplateSummaryLabel {
	if o == nil || o.LabelAssociations == nil {
		var ret []TemplateSummaryLabel
		return ret
	}
	return *o.LabelAssociations
}

// GetLabelAssociationsOk returns a tuple with the LabelAssociations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryTelegraf) GetLabelAssociationsOk() (*[]TemplateSummaryLabel, bool) {
	if o == nil || o.LabelAssociations == nil {
		return nil, false
	}
	return o.LabelAssociations, true
}

// HasLabelAssociations returns a boolean if a field has been set.
func (o *TemplateSummaryTelegraf) HasLabelAssociations() bool {
	if o != nil && o.LabelAssociations != nil {
		return true
	}

	return false
}

// SetLabelAssociations gets a reference to the given []TemplateSummaryLabel and assigns it to the LabelAssociations field.
func (o *TemplateSummaryTelegraf) SetLabelAssociations(v []TemplateSummaryLabel) {
	o.LabelAssociations = &v
}

// GetTelegrafConfig returns the TelegrafConfig field value if set, zero value otherwise.
func (o *TemplateSummaryTelegraf) GetTelegrafConfig() TemplateSummaryTelegrafConfig {
	if o == nil || o.TelegrafConfig == nil {
		var ret TemplateSummaryTelegrafConfig
		return ret
	}
	return *o.TelegrafConfig
}

// GetTelegrafConfigOk returns a tuple with the TelegrafConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryTelegraf) GetTelegrafConfigOk() (*TemplateSummaryTelegrafConfig, bool) {
	if o == nil || o.TelegrafConfig == nil {
		return nil, false
	}
	return o.TelegrafConfig, true
}

// HasTelegrafConfig returns a boolean if a field has been set.
func (o *TemplateSummaryTelegraf) HasTelegrafConfig() bool {
	if o != nil && o.TelegrafConfig != nil {
		return true
	}

	return false
}

// SetTelegrafConfig gets a reference to the given TemplateSummaryTelegrafConfig and assigns it to the TelegrafConfig field.
func (o *TemplateSummaryTelegraf) SetTelegrafConfig(v TemplateSummaryTelegrafConfig) {
	o.TelegrafConfig = &v
}

func (o TemplateSummaryTelegraf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}
	if o.TemplateMetaName != nil {
		toSerialize["templateMetaName"] = o.TemplateMetaName
	}
	if o.EnvReferences != nil {
		toSerialize["envReferences"] = o.EnvReferences
	}
	if o.LabelAssociations != nil {
		toSerialize["labelAssociations"] = o.LabelAssociations
	}
	if o.TelegrafConfig != nil {
		toSerialize["telegrafConfig"] = o.TelegrafConfig
	}
	return json.Marshal(toSerialize)
}

type NullableTemplateSummaryTelegraf struct {
	value *TemplateSummaryTelegraf
	isSet bool
}

func (v NullableTemplateSummaryTelegraf) Get() *TemplateSummaryTelegraf {
	return v.value
}

func (v *NullableTemplateSummaryTelegraf) Set(val *TemplateSummaryTelegraf) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateSummaryTelegraf) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateSummaryTelegraf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateSummaryTelegraf(val *TemplateSummaryTelegraf) *NullableTemplateSummaryTelegraf {
	return &NullableTemplateSummaryTelegraf{value: val, isSet: true}
}

func (v NullableTemplateSummaryTelegraf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateSummaryTelegraf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
