/*
 * Subset of Influx API covered by Influx CLI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// PostOrganizationRequest struct for PostOrganizationRequest
type PostOrganizationRequest struct {
	// The name of the organization.
	Name string `json:"name" yaml:"name"`
	// The description of the organization.
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`
}

// NewPostOrganizationRequest instantiates a new PostOrganizationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostOrganizationRequest(name string) *PostOrganizationRequest {
	this := PostOrganizationRequest{}
	this.Name = name
	return &this
}

// NewPostOrganizationRequestWithDefaults instantiates a new PostOrganizationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostOrganizationRequestWithDefaults() *PostOrganizationRequest {
	this := PostOrganizationRequest{}
	return &this
}

// GetName returns the Name field value
func (o *PostOrganizationRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PostOrganizationRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PostOrganizationRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PostOrganizationRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostOrganizationRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PostOrganizationRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PostOrganizationRequest) SetDescription(v string) {
	o.Description = &v
}

func (o PostOrganizationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullablePostOrganizationRequest struct {
	value *PostOrganizationRequest
	isSet bool
}

func (v NullablePostOrganizationRequest) Get() *PostOrganizationRequest {
	return v.value
}

func (v *NullablePostOrganizationRequest) Set(val *PostOrganizationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostOrganizationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostOrganizationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostOrganizationRequest(val *PostOrganizationRequest) *NullablePostOrganizationRequest {
	return &NullablePostOrganizationRequest{value: val, isSet: true}
}

func (v NullablePostOrganizationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostOrganizationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
