/*
 * Subset of Influx API covered by Influx CLI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// OrganizationLinks struct for OrganizationLinks
type OrganizationLinks struct {
	// URI of resource.
	Self *string `json:"self,omitempty" yaml:"self,omitempty"`
	// URI of resource.
	Members *string `json:"members,omitempty" yaml:"members,omitempty"`
	// URI of resource.
	Owners *string `json:"owners,omitempty" yaml:"owners,omitempty"`
	// URI of resource.
	Labels *string `json:"labels,omitempty" yaml:"labels,omitempty"`
	// URI of resource.
	Secrets *string `json:"secrets,omitempty" yaml:"secrets,omitempty"`
	// URI of resource.
	Buckets *string `json:"buckets,omitempty" yaml:"buckets,omitempty"`
	// URI of resource.
	Tasks *string `json:"tasks,omitempty" yaml:"tasks,omitempty"`
	// URI of resource.
	Dashboards *string `json:"dashboards,omitempty" yaml:"dashboards,omitempty"`
}

// NewOrganizationLinks instantiates a new OrganizationLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationLinks() *OrganizationLinks {
	this := OrganizationLinks{}
	return &this
}

// NewOrganizationLinksWithDefaults instantiates a new OrganizationLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationLinksWithDefaults() *OrganizationLinks {
	this := OrganizationLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *OrganizationLinks) GetSelf() string {
	if o == nil || o.Self == nil {
		var ret string
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetSelfOk() (*string, bool) {
	if o == nil || o.Self == nil {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *OrganizationLinks) HasSelf() bool {
	if o != nil && o.Self != nil {
		return true
	}

	return false
}

// SetSelf gets a reference to the given string and assigns it to the Self field.
func (o *OrganizationLinks) SetSelf(v string) {
	o.Self = &v
}

// GetMembers returns the Members field value if set, zero value otherwise.
func (o *OrganizationLinks) GetMembers() string {
	if o == nil || o.Members == nil {
		var ret string
		return ret
	}
	return *o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetMembersOk() (*string, bool) {
	if o == nil || o.Members == nil {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *OrganizationLinks) HasMembers() bool {
	if o != nil && o.Members != nil {
		return true
	}

	return false
}

// SetMembers gets a reference to the given string and assigns it to the Members field.
func (o *OrganizationLinks) SetMembers(v string) {
	o.Members = &v
}

// GetOwners returns the Owners field value if set, zero value otherwise.
func (o *OrganizationLinks) GetOwners() string {
	if o == nil || o.Owners == nil {
		var ret string
		return ret
	}
	return *o.Owners
}

// GetOwnersOk returns a tuple with the Owners field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetOwnersOk() (*string, bool) {
	if o == nil || o.Owners == nil {
		return nil, false
	}
	return o.Owners, true
}

// HasOwners returns a boolean if a field has been set.
func (o *OrganizationLinks) HasOwners() bool {
	if o != nil && o.Owners != nil {
		return true
	}

	return false
}

// SetOwners gets a reference to the given string and assigns it to the Owners field.
func (o *OrganizationLinks) SetOwners(v string) {
	o.Owners = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *OrganizationLinks) GetLabels() string {
	if o == nil || o.Labels == nil {
		var ret string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetLabelsOk() (*string, bool) {
	if o == nil || o.Labels == nil {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *OrganizationLinks) HasLabels() bool {
	if o != nil && o.Labels != nil {
		return true
	}

	return false
}

// SetLabels gets a reference to the given string and assigns it to the Labels field.
func (o *OrganizationLinks) SetLabels(v string) {
	o.Labels = &v
}

// GetSecrets returns the Secrets field value if set, zero value otherwise.
func (o *OrganizationLinks) GetSecrets() string {
	if o == nil || o.Secrets == nil {
		var ret string
		return ret
	}
	return *o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetSecretsOk() (*string, bool) {
	if o == nil || o.Secrets == nil {
		return nil, false
	}
	return o.Secrets, true
}

// HasSecrets returns a boolean if a field has been set.
func (o *OrganizationLinks) HasSecrets() bool {
	if o != nil && o.Secrets != nil {
		return true
	}

	return false
}

// SetSecrets gets a reference to the given string and assigns it to the Secrets field.
func (o *OrganizationLinks) SetSecrets(v string) {
	o.Secrets = &v
}

// GetBuckets returns the Buckets field value if set, zero value otherwise.
func (o *OrganizationLinks) GetBuckets() string {
	if o == nil || o.Buckets == nil {
		var ret string
		return ret
	}
	return *o.Buckets
}

// GetBucketsOk returns a tuple with the Buckets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetBucketsOk() (*string, bool) {
	if o == nil || o.Buckets == nil {
		return nil, false
	}
	return o.Buckets, true
}

// HasBuckets returns a boolean if a field has been set.
func (o *OrganizationLinks) HasBuckets() bool {
	if o != nil && o.Buckets != nil {
		return true
	}

	return false
}

// SetBuckets gets a reference to the given string and assigns it to the Buckets field.
func (o *OrganizationLinks) SetBuckets(v string) {
	o.Buckets = &v
}

// GetTasks returns the Tasks field value if set, zero value otherwise.
func (o *OrganizationLinks) GetTasks() string {
	if o == nil || o.Tasks == nil {
		var ret string
		return ret
	}
	return *o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetTasksOk() (*string, bool) {
	if o == nil || o.Tasks == nil {
		return nil, false
	}
	return o.Tasks, true
}

// HasTasks returns a boolean if a field has been set.
func (o *OrganizationLinks) HasTasks() bool {
	if o != nil && o.Tasks != nil {
		return true
	}

	return false
}

// SetTasks gets a reference to the given string and assigns it to the Tasks field.
func (o *OrganizationLinks) SetTasks(v string) {
	o.Tasks = &v
}

// GetDashboards returns the Dashboards field value if set, zero value otherwise.
func (o *OrganizationLinks) GetDashboards() string {
	if o == nil || o.Dashboards == nil {
		var ret string
		return ret
	}
	return *o.Dashboards
}

// GetDashboardsOk returns a tuple with the Dashboards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationLinks) GetDashboardsOk() (*string, bool) {
	if o == nil || o.Dashboards == nil {
		return nil, false
	}
	return o.Dashboards, true
}

// HasDashboards returns a boolean if a field has been set.
func (o *OrganizationLinks) HasDashboards() bool {
	if o != nil && o.Dashboards != nil {
		return true
	}

	return false
}

// SetDashboards gets a reference to the given string and assigns it to the Dashboards field.
func (o *OrganizationLinks) SetDashboards(v string) {
	o.Dashboards = &v
}

func (o OrganizationLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Self != nil {
		toSerialize["self"] = o.Self
	}
	if o.Members != nil {
		toSerialize["members"] = o.Members
	}
	if o.Owners != nil {
		toSerialize["owners"] = o.Owners
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Secrets != nil {
		toSerialize["secrets"] = o.Secrets
	}
	if o.Buckets != nil {
		toSerialize["buckets"] = o.Buckets
	}
	if o.Tasks != nil {
		toSerialize["tasks"] = o.Tasks
	}
	if o.Dashboards != nil {
		toSerialize["dashboards"] = o.Dashboards
	}
	return json.Marshal(toSerialize)
}

type NullableOrganizationLinks struct {
	value *OrganizationLinks
	isSet bool
}

func (v NullableOrganizationLinks) Get() *OrganizationLinks {
	return v.value
}

func (v *NullableOrganizationLinks) Set(val *OrganizationLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationLinks(val *OrganizationLinks) *NullableOrganizationLinks {
	return &NullableOrganizationLinks{value: val, isSet: true}
}

func (v NullableOrganizationLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
