/*
 * Subset of Influx API covered by Influx CLI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// TemplateSummaryDiffTask struct for TemplateSummaryDiffTask
type TemplateSummaryDiffTask struct {
	Kind             string                         `json:"kind" yaml:"kind"`
	StateStatus      string                         `json:"stateStatus" yaml:"stateStatus"`
	Id               string                         `json:"id" yaml:"id"`
	TemplateMetaName string                         `json:"templateMetaName" yaml:"templateMetaName"`
	New              *TemplateSummaryDiffTaskFields `json:"new,omitempty" yaml:"new,omitempty"`
	Old              *TemplateSummaryDiffTaskFields `json:"old,omitempty" yaml:"old,omitempty"`
}

// NewTemplateSummaryDiffTask instantiates a new TemplateSummaryDiffTask object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateSummaryDiffTask(kind string, stateStatus string, id string, templateMetaName string) *TemplateSummaryDiffTask {
	this := TemplateSummaryDiffTask{}
	this.Kind = kind
	this.StateStatus = stateStatus
	this.Id = id
	this.TemplateMetaName = templateMetaName
	return &this
}

// NewTemplateSummaryDiffTaskWithDefaults instantiates a new TemplateSummaryDiffTask object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateSummaryDiffTaskWithDefaults() *TemplateSummaryDiffTask {
	this := TemplateSummaryDiffTask{}
	return &this
}

// GetKind returns the Kind field value
func (o *TemplateSummaryDiffTask) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryDiffTask) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *TemplateSummaryDiffTask) SetKind(v string) {
	o.Kind = v
}

// GetStateStatus returns the StateStatus field value
func (o *TemplateSummaryDiffTask) GetStateStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StateStatus
}

// GetStateStatusOk returns a tuple with the StateStatus field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryDiffTask) GetStateStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StateStatus, true
}

// SetStateStatus sets field value
func (o *TemplateSummaryDiffTask) SetStateStatus(v string) {
	o.StateStatus = v
}

// GetId returns the Id field value
func (o *TemplateSummaryDiffTask) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryDiffTask) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TemplateSummaryDiffTask) SetId(v string) {
	o.Id = v
}

// GetTemplateMetaName returns the TemplateMetaName field value
func (o *TemplateSummaryDiffTask) GetTemplateMetaName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateMetaName
}

// GetTemplateMetaNameOk returns a tuple with the TemplateMetaName field value
// and a boolean to check if the value has been set.
func (o *TemplateSummaryDiffTask) GetTemplateMetaNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateMetaName, true
}

// SetTemplateMetaName sets field value
func (o *TemplateSummaryDiffTask) SetTemplateMetaName(v string) {
	o.TemplateMetaName = v
}

// GetNew returns the New field value if set, zero value otherwise.
func (o *TemplateSummaryDiffTask) GetNew() TemplateSummaryDiffTaskFields {
	if o == nil || o.New == nil {
		var ret TemplateSummaryDiffTaskFields
		return ret
	}
	return *o.New
}

// GetNewOk returns a tuple with the New field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryDiffTask) GetNewOk() (*TemplateSummaryDiffTaskFields, bool) {
	if o == nil || o.New == nil {
		return nil, false
	}
	return o.New, true
}

// HasNew returns a boolean if a field has been set.
func (o *TemplateSummaryDiffTask) HasNew() bool {
	if o != nil && o.New != nil {
		return true
	}

	return false
}

// SetNew gets a reference to the given TemplateSummaryDiffTaskFields and assigns it to the New field.
func (o *TemplateSummaryDiffTask) SetNew(v TemplateSummaryDiffTaskFields) {
	o.New = &v
}

// GetOld returns the Old field value if set, zero value otherwise.
func (o *TemplateSummaryDiffTask) GetOld() TemplateSummaryDiffTaskFields {
	if o == nil || o.Old == nil {
		var ret TemplateSummaryDiffTaskFields
		return ret
	}
	return *o.Old
}

// GetOldOk returns a tuple with the Old field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryDiffTask) GetOldOk() (*TemplateSummaryDiffTaskFields, bool) {
	if o == nil || o.Old == nil {
		return nil, false
	}
	return o.Old, true
}

// HasOld returns a boolean if a field has been set.
func (o *TemplateSummaryDiffTask) HasOld() bool {
	if o != nil && o.Old != nil {
		return true
	}

	return false
}

// SetOld gets a reference to the given TemplateSummaryDiffTaskFields and assigns it to the Old field.
func (o *TemplateSummaryDiffTask) SetOld(v TemplateSummaryDiffTaskFields) {
	o.Old = &v
}

func (o TemplateSummaryDiffTask) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if true {
		toSerialize["stateStatus"] = o.StateStatus
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["templateMetaName"] = o.TemplateMetaName
	}
	if o.New != nil {
		toSerialize["new"] = o.New
	}
	if o.Old != nil {
		toSerialize["old"] = o.Old
	}
	return json.Marshal(toSerialize)
}

type NullableTemplateSummaryDiffTask struct {
	value *TemplateSummaryDiffTask
	isSet bool
}

func (v NullableTemplateSummaryDiffTask) Get() *TemplateSummaryDiffTask {
	return v.value
}

func (v *NullableTemplateSummaryDiffTask) Set(val *TemplateSummaryDiffTask) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateSummaryDiffTask) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateSummaryDiffTask) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateSummaryDiffTask(val *TemplateSummaryDiffTask) *NullableTemplateSummaryDiffTask {
	return &NullableTemplateSummaryDiffTask{value: val, isSet: true}
}

func (v NullableTemplateSummaryDiffTask) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateSummaryDiffTask) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
