/*
 * Subset of Influx API covered by Influx CLI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// TemplateSummaryResources struct for TemplateSummaryResources
type TemplateSummaryResources struct {
	Buckets               *[]TemplateSummaryBucket               `json:"buckets,omitempty"`
	Checks                *[]TemplateSummaryCheck                `json:"checks,omitempty"`
	Dashboards            *[]TemplateSummaryDashboard            `json:"dashboards,omitempty"`
	Labels                *[]TemplateSummaryLabel                `json:"labels,omitempty"`
	LabelMappings         *[]TemplateSummaryLabelMapping         `json:"labelMappings,omitempty"`
	MissingEnvRefs        *[]string                              `json:"missingEnvRefs,omitempty"`
	MissingSecrets        *[]string                              `json:"missingSecrets,omitempty"`
	NotificationEndpoints *[]TemplateSummaryNotificationEndpoint `json:"notificationEndpoints,omitempty"`
	NotificationRules     *[]TemplateSummaryNotificationRule     `json:"notificationRules,omitempty"`
	Tasks                 *[]TemplateSummaryTask                 `json:"tasks,omitempty"`
	TelegrafConfigs       *[]TemplateSummaryTelegraf             `json:"telegrafConfigs,omitempty"`
	Variables             *[]TemplateSummaryVariable             `json:"variables,omitempty"`
}

// NewTemplateSummaryResources instantiates a new TemplateSummaryResources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateSummaryResources() *TemplateSummaryResources {
	this := TemplateSummaryResources{}
	return &this
}

// NewTemplateSummaryResourcesWithDefaults instantiates a new TemplateSummaryResources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateSummaryResourcesWithDefaults() *TemplateSummaryResources {
	this := TemplateSummaryResources{}
	return &this
}

// GetBuckets returns the Buckets field value if set, zero value otherwise.
func (o *TemplateSummaryResources) GetBuckets() []TemplateSummaryBucket {
	if o == nil || o.Buckets == nil {
		var ret []TemplateSummaryBucket
		return ret
	}
	return *o.Buckets
}

// GetBucketsOk returns a tuple with the Buckets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResources) GetBucketsOk() (*[]TemplateSummaryBucket, bool) {
	if o == nil || o.Buckets == nil {
		return nil, false
	}
	return o.Buckets, true
}

// HasBuckets returns a boolean if a field has been set.
func (o *TemplateSummaryResources) HasBuckets() bool {
	if o != nil && o.Buckets != nil {
		return true
	}

	return false
}

// SetBuckets gets a reference to the given []TemplateSummaryBucket and assigns it to the Buckets field.
func (o *TemplateSummaryResources) SetBuckets(v []TemplateSummaryBucket) {
	o.Buckets = &v
}

// GetChecks returns the Checks field value if set, zero value otherwise.
func (o *TemplateSummaryResources) GetChecks() []TemplateSummaryCheck {
	if o == nil || o.Checks == nil {
		var ret []TemplateSummaryCheck
		return ret
	}
	return *o.Checks
}

// GetChecksOk returns a tuple with the Checks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResources) GetChecksOk() (*[]TemplateSummaryCheck, bool) {
	if o == nil || o.Checks == nil {
		return nil, false
	}
	return o.Checks, true
}

// HasChecks returns a boolean if a field has been set.
func (o *TemplateSummaryResources) HasChecks() bool {
	if o != nil && o.Checks != nil {
		return true
	}

	return false
}

// SetChecks gets a reference to the given []TemplateSummaryCheck and assigns it to the Checks field.
func (o *TemplateSummaryResources) SetChecks(v []TemplateSummaryCheck) {
	o.Checks = &v
}

// GetDashboards returns the Dashboards field value if set, zero value otherwise.
func (o *TemplateSummaryResources) GetDashboards() []TemplateSummaryDashboard {
	if o == nil || o.Dashboards == nil {
		var ret []TemplateSummaryDashboard
		return ret
	}
	return *o.Dashboards
}

// GetDashboardsOk returns a tuple with the Dashboards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResources) GetDashboardsOk() (*[]TemplateSummaryDashboard, bool) {
	if o == nil || o.Dashboards == nil {
		return nil, false
	}
	return o.Dashboards, true
}

// HasDashboards returns a boolean if a field has been set.
func (o *TemplateSummaryResources) HasDashboards() bool {
	if o != nil && o.Dashboards != nil {
		return true
	}

	return false
}

// SetDashboards gets a reference to the given []TemplateSummaryDashboard and assigns it to the Dashboards field.
func (o *TemplateSummaryResources) SetDashboards(v []TemplateSummaryDashboard) {
	o.Dashboards = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *TemplateSummaryResources) GetLabels() []TemplateSummaryLabel {
	if o == nil || o.Labels == nil {
		var ret []TemplateSummaryLabel
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResources) GetLabelsOk() (*[]TemplateSummaryLabel, bool) {
	if o == nil || o.Labels == nil {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *TemplateSummaryResources) HasLabels() bool {
	if o != nil && o.Labels != nil {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []TemplateSummaryLabel and assigns it to the Labels field.
func (o *TemplateSummaryResources) SetLabels(v []TemplateSummaryLabel) {
	o.Labels = &v
}

// GetLabelMappings returns the LabelMappings field value if set, zero value otherwise.
func (o *TemplateSummaryResources) GetLabelMappings() []TemplateSummaryLabelMapping {
	if o == nil || o.LabelMappings == nil {
		var ret []TemplateSummaryLabelMapping
		return ret
	}
	return *o.LabelMappings
}

// GetLabelMappingsOk returns a tuple with the LabelMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResources) GetLabelMappingsOk() (*[]TemplateSummaryLabelMapping, bool) {
	if o == nil || o.LabelMappings == nil {
		return nil, false
	}
	return o.LabelMappings, true
}

// HasLabelMappings returns a boolean if a field has been set.
func (o *TemplateSummaryResources) HasLabelMappings() bool {
	if o != nil && o.LabelMappings != nil {
		return true
	}

	return false
}

// SetLabelMappings gets a reference to the given []TemplateSummaryLabelMapping and assigns it to the LabelMappings field.
func (o *TemplateSummaryResources) SetLabelMappings(v []TemplateSummaryLabelMapping) {
	o.LabelMappings = &v
}

// GetMissingEnvRefs returns the MissingEnvRefs field value if set, zero value otherwise.
func (o *TemplateSummaryResources) GetMissingEnvRefs() []string {
	if o == nil || o.MissingEnvRefs == nil {
		var ret []string
		return ret
	}
	return *o.MissingEnvRefs
}

// GetMissingEnvRefsOk returns a tuple with the MissingEnvRefs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResources) GetMissingEnvRefsOk() (*[]string, bool) {
	if o == nil || o.MissingEnvRefs == nil {
		return nil, false
	}
	return o.MissingEnvRefs, true
}

// HasMissingEnvRefs returns a boolean if a field has been set.
func (o *TemplateSummaryResources) HasMissingEnvRefs() bool {
	if o != nil && o.MissingEnvRefs != nil {
		return true
	}

	return false
}

// SetMissingEnvRefs gets a reference to the given []string and assigns it to the MissingEnvRefs field.
func (o *TemplateSummaryResources) SetMissingEnvRefs(v []string) {
	o.MissingEnvRefs = &v
}

// GetMissingSecrets returns the MissingSecrets field value if set, zero value otherwise.
func (o *TemplateSummaryResources) GetMissingSecrets() []string {
	if o == nil || o.MissingSecrets == nil {
		var ret []string
		return ret
	}
	return *o.MissingSecrets
}

// GetMissingSecretsOk returns a tuple with the MissingSecrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResources) GetMissingSecretsOk() (*[]string, bool) {
	if o == nil || o.MissingSecrets == nil {
		return nil, false
	}
	return o.MissingSecrets, true
}

// HasMissingSecrets returns a boolean if a field has been set.
func (o *TemplateSummaryResources) HasMissingSecrets() bool {
	if o != nil && o.MissingSecrets != nil {
		return true
	}

	return false
}

// SetMissingSecrets gets a reference to the given []string and assigns it to the MissingSecrets field.
func (o *TemplateSummaryResources) SetMissingSecrets(v []string) {
	o.MissingSecrets = &v
}

// GetNotificationEndpoints returns the NotificationEndpoints field value if set, zero value otherwise.
func (o *TemplateSummaryResources) GetNotificationEndpoints() []TemplateSummaryNotificationEndpoint {
	if o == nil || o.NotificationEndpoints == nil {
		var ret []TemplateSummaryNotificationEndpoint
		return ret
	}
	return *o.NotificationEndpoints
}

// GetNotificationEndpointsOk returns a tuple with the NotificationEndpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResources) GetNotificationEndpointsOk() (*[]TemplateSummaryNotificationEndpoint, bool) {
	if o == nil || o.NotificationEndpoints == nil {
		return nil, false
	}
	return o.NotificationEndpoints, true
}

// HasNotificationEndpoints returns a boolean if a field has been set.
func (o *TemplateSummaryResources) HasNotificationEndpoints() bool {
	if o != nil && o.NotificationEndpoints != nil {
		return true
	}

	return false
}

// SetNotificationEndpoints gets a reference to the given []TemplateSummaryNotificationEndpoint and assigns it to the NotificationEndpoints field.
func (o *TemplateSummaryResources) SetNotificationEndpoints(v []TemplateSummaryNotificationEndpoint) {
	o.NotificationEndpoints = &v
}

// GetNotificationRules returns the NotificationRules field value if set, zero value otherwise.
func (o *TemplateSummaryResources) GetNotificationRules() []TemplateSummaryNotificationRule {
	if o == nil || o.NotificationRules == nil {
		var ret []TemplateSummaryNotificationRule
		return ret
	}
	return *o.NotificationRules
}

// GetNotificationRulesOk returns a tuple with the NotificationRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResources) GetNotificationRulesOk() (*[]TemplateSummaryNotificationRule, bool) {
	if o == nil || o.NotificationRules == nil {
		return nil, false
	}
	return o.NotificationRules, true
}

// HasNotificationRules returns a boolean if a field has been set.
func (o *TemplateSummaryResources) HasNotificationRules() bool {
	if o != nil && o.NotificationRules != nil {
		return true
	}

	return false
}

// SetNotificationRules gets a reference to the given []TemplateSummaryNotificationRule and assigns it to the NotificationRules field.
func (o *TemplateSummaryResources) SetNotificationRules(v []TemplateSummaryNotificationRule) {
	o.NotificationRules = &v
}

// GetTasks returns the Tasks field value if set, zero value otherwise.
func (o *TemplateSummaryResources) GetTasks() []TemplateSummaryTask {
	if o == nil || o.Tasks == nil {
		var ret []TemplateSummaryTask
		return ret
	}
	return *o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResources) GetTasksOk() (*[]TemplateSummaryTask, bool) {
	if o == nil || o.Tasks == nil {
		return nil, false
	}
	return o.Tasks, true
}

// HasTasks returns a boolean if a field has been set.
func (o *TemplateSummaryResources) HasTasks() bool {
	if o != nil && o.Tasks != nil {
		return true
	}

	return false
}

// SetTasks gets a reference to the given []TemplateSummaryTask and assigns it to the Tasks field.
func (o *TemplateSummaryResources) SetTasks(v []TemplateSummaryTask) {
	o.Tasks = &v
}

// GetTelegrafConfigs returns the TelegrafConfigs field value if set, zero value otherwise.
func (o *TemplateSummaryResources) GetTelegrafConfigs() []TemplateSummaryTelegraf {
	if o == nil || o.TelegrafConfigs == nil {
		var ret []TemplateSummaryTelegraf
		return ret
	}
	return *o.TelegrafConfigs
}

// GetTelegrafConfigsOk returns a tuple with the TelegrafConfigs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResources) GetTelegrafConfigsOk() (*[]TemplateSummaryTelegraf, bool) {
	if o == nil || o.TelegrafConfigs == nil {
		return nil, false
	}
	return o.TelegrafConfigs, true
}

// HasTelegrafConfigs returns a boolean if a field has been set.
func (o *TemplateSummaryResources) HasTelegrafConfigs() bool {
	if o != nil && o.TelegrafConfigs != nil {
		return true
	}

	return false
}

// SetTelegrafConfigs gets a reference to the given []TemplateSummaryTelegraf and assigns it to the TelegrafConfigs field.
func (o *TemplateSummaryResources) SetTelegrafConfigs(v []TemplateSummaryTelegraf) {
	o.TelegrafConfigs = &v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *TemplateSummaryResources) GetVariables() []TemplateSummaryVariable {
	if o == nil || o.Variables == nil {
		var ret []TemplateSummaryVariable
		return ret
	}
	return *o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateSummaryResources) GetVariablesOk() (*[]TemplateSummaryVariable, bool) {
	if o == nil || o.Variables == nil {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *TemplateSummaryResources) HasVariables() bool {
	if o != nil && o.Variables != nil {
		return true
	}

	return false
}

// SetVariables gets a reference to the given []TemplateSummaryVariable and assigns it to the Variables field.
func (o *TemplateSummaryResources) SetVariables(v []TemplateSummaryVariable) {
	o.Variables = &v
}

func (o TemplateSummaryResources) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Buckets != nil {
		toSerialize["buckets"] = o.Buckets
	}
	if o.Checks != nil {
		toSerialize["checks"] = o.Checks
	}
	if o.Dashboards != nil {
		toSerialize["dashboards"] = o.Dashboards
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.LabelMappings != nil {
		toSerialize["labelMappings"] = o.LabelMappings
	}
	if o.MissingEnvRefs != nil {
		toSerialize["missingEnvRefs"] = o.MissingEnvRefs
	}
	if o.MissingSecrets != nil {
		toSerialize["missingSecrets"] = o.MissingSecrets
	}
	if o.NotificationEndpoints != nil {
		toSerialize["notificationEndpoints"] = o.NotificationEndpoints
	}
	if o.NotificationRules != nil {
		toSerialize["notificationRules"] = o.NotificationRules
	}
	if o.Tasks != nil {
		toSerialize["tasks"] = o.Tasks
	}
	if o.TelegrafConfigs != nil {
		toSerialize["telegrafConfigs"] = o.TelegrafConfigs
	}
	if o.Variables != nil {
		toSerialize["variables"] = o.Variables
	}
	return json.Marshal(toSerialize)
}

type NullableTemplateSummaryResources struct {
	value *TemplateSummaryResources
	isSet bool
}

func (v NullableTemplateSummaryResources) Get() *TemplateSummaryResources {
	return v.value
}

func (v *NullableTemplateSummaryResources) Set(val *TemplateSummaryResources) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateSummaryResources) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateSummaryResources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateSummaryResources(val *TemplateSummaryResources) *NullableTemplateSummaryResources {
	return &NullableTemplateSummaryResources{value: val, isSet: true}
}

func (v NullableTemplateSummaryResources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateSummaryResources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
